### ISSUE TITLE
Design Digital Assets for Webmaker Launch 

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#34] opened 2015-06-08 22:12 UTC
Driver: @edrushka
Design lead: @jaykappa
QA: @cassiemc
CC: @secretrobotron @HPaulJohnson

These will be created using the [core assets](https://github.com/mozilla/webmaker-launch/issues/32).
#### P1 Must Haves
- [x] ~~Snippet icon~~ <-- being done by Moco
- [x] MoFo email callout
- [x] Facebook graphic
- [x] Twitter graphic
#### P2 Nice to Haves
- [x] [Partner digital assets](https://github.com/mozilla/webmaker-launch/issues/43)
- [x] Teach.org promo
- [x] Web banners 
- [x] Downloadable logos
#### P3 Only if there's time
- [ ] ~~Snapchat graphic~~ <-- no time
- [ ] ~~Youtube pre-roll~~ <-- no time
- [ ] ~~LAN House digital assets~~ <-- no time

**Comment by xmatthewx** [comment] 2015-06-08 22:19
The value, importance, and complexity of these digital assets is higher than the print assets. Seems like we should have @lovegushwa's talent here and across the P1s to make sure that we design a consistent system that works across print and digital.

**Comment by cassiemc** [comment] 2015-06-09 00:43
@xmatthewx – Agreed that @lovegushwa should drive the work. I thought it'd be good for him to tackle print stuff first and establish styles/systems that a contractor can use, and he'll be involved in reviewing the contractor's work. It's useful to get the print stuff out first since it needs to go to production, and I actually don't see anything that complex in the P1s. If you disagree we should chat asap.

**Comment by cassiemc** [comment] 2015-06-12 19:44
The contractor, Jay of [Brand Muller](http://brandmuller.com/), and contract are in place! Ready to start work on Tuesday. We'll be looking for at least one finalized print asset from @lovegushwa by EOD Monday so we can have a kickoff and get Jay started on Tuesday. 

cc @edrushka @thisandagain @secretrobotron @HPaulJohnson @xmatthewx

**Comment by thisandagain** [comment] 2015-06-12 22:00
Awesome. Thanks for the update!

**Comment by jaykappa** [comment] 2015-06-19 12:35
![2015-webmaker-facebook_twitter-eng-v1](https://cloud.githubusercontent.com/assets/1036635/8253424/9ec57a1c-165d-11e5-89ab-ec99ae0ad612.png)

![2015-webmaker-facebook_twitter-eng-v2](https://cloud.githubusercontent.com/assets/1036635/8253427/a60a0568-165d-11e5-958a-41ab1063289d.png)

The reason why I've combined everything for this initial presentation is because of how similar the Twitter and Facebook assets are going to be. Plus, the poster is still in WIP...What I've done so far is imaginative extrapolation based on the Google Play Store assets, so I figured we could narrow down which comp styles are preferred. The feedback will help me in developing clear-cut directions for Twitter and Facebook respectively.

At this point, all of the designs are quite flexible and interchangeable, including the various icons I've drawn to represent the concept of "downloading" (the app). At the same time if we need to nix it no problems as well.

You will notice that the larger V2 designs are either direct or very similar interpretations of the smaller V1s. I think it makes more sense that way, because the smallest assets in a set help define what should, can and will fit (content-wise) across the dimension board. The V2 designs do look a little vacant, but I was hesitant on adding random content and breaking out of the assumed branding.

R? @cassiemc @edrushka

**Comment by edrushka** [comment] 2015-06-20 00:02
@jaykappa and I reviewed these during our stand today, and I got some further feedback from @HPaulJohnson:
- love showing the phone
- love the logo with wordmark
- prefer showing people on the phone screen over landscapes (I'll attach screenshot we're using on the landing page).
- no value proposition (tagline) needed on the small squares, since space is limited
- let's go with the chevrons for the download icon
- a bit less hand (overall)

Jay, maybe you want to throw the next set up on Redpen so @cassiemc  can give specific feedback. Might be confusing to try to do that asynchronously on Github.

**Comment by edrushka** [comment] 2015-06-20 00:02
![hero 2x](https://cloud.githubusercontent.com/assets/4515662/8265034/f21d8a50-16a4-11e5-95dd-0b87b25ec18c.png)

**Comment by jaykappa** [comment] 2015-06-20 01:03
@edrushka Thanks for the feedback I'll post a RedPen for the revisions and a link here afterward.

**Comment by jaykappa** [comment] 2015-06-20 16:26
@edrushka is it possible to get a crop of this screenshot without the phone and a bit length (vertically) by about 500px ?

**Comment by edrushka** [comment] 2015-06-20 17:12
@vasquez @cassiemc could either of you get that for @jaykappa? Or direct me to who I should ping? Thanks!

**Comment by cassiemc** [comment] 2015-06-22 15:31
@edrushka – @vazquez (typo above) should be able to get that, or @lovegushwa.

**Comment by jaykappa** [comment] 2015-06-22 20:53
Opened a RedPen for the Facebook and Twitter assets:
https://redpen.io/jv101e34ce561d05cb

R? @cassiemc @edrushka @lovegushwa 

Some general notes:

## 200 x 200
- removed the rejected designs from the screenshots
- feedback said that I could ditch the tagline to conserve space, but in some cases, tagline was kept to help balance out the composition (sometimes the wordmark logo and phone create whitespace that is slightly difficult to balance, visually-speaking)
- almost all of the Hand designs now have non-Hand alternates
- maybe the no-tagline options would be best for Twitter and Facebook but with tagline for MoFO email?

## larger versions
- revised designs now pair nicely with most of the 200 x 200 options (in some cases, might require a quick colour palette match-up)
- also, still have the option of designing new larger ones to match whatever 200x200's are picked

**Comment by jaykappa** [comment] 2015-06-22 20:59
Mofo Email Callout
Opened a RedPen for the asset:
https://redpen.io/qw6b3d43d04df3d468
- after revising designs for Twitter and FB assets, the busier compositions with the tagline could work well for MoFo callout
- took the options that could work best and re-sized them into the three requested dimensions (200x 200, 500x500, 800x800)

R? @cassiemc @edrushka @lovegushwa

**Comment by jaykappa** [comment] 2015-06-22 22:32
**Teach.Org Banner**

Opened a RedPen for the asset:
https://redpen.io/uh0fcccfcd8440a057

It might be too adventurous based on the guidelines but with some strong CSS it can work, but the limitations for what adjustments are possible for banner absolute positioning is of a bit unknown. If the positioning is very strict then the options are more limited to just the word or brand mark (because the brand name is seen in the content).

R? @cassiemc @edrushka @lovegushwa

**Comment by yofiesetiawan** [comment] 2015-06-24 14:55
Hi, do we have any color guidelines?

**Comment by jaykappa** [comment] 2015-06-25 19:32
Made some alterations based on our convo today @edrushka @cassiemc @lovegushwa 

**Mofo Email Callout/Facebook/Twitter:**
https://redpen.io/jmd1fe0a33abe69672
![2015-webmaker-mofo-eng-v2](https://cloud.githubusercontent.com/assets/1036635/8363746/175404bc-1b4f-11e5-8f49-3d7fb370ec80.jpg)

**Teach.Org Banner:**
https://redpen.io/cj5346b0097f53c477
![2015-webmaker-teachorg-eng-v2](https://cloud.githubusercontent.com/assets/1036635/8363750/212ffb08-1b4f-11e5-8029-89639d399463.jpg)
- Pending alterations based on font weights and print work later today of course this would be for layout selection.
  Also I think the Sketch app folder that went up on Drive didn't have the actual artwork file only Font files.

**Comment by edrushka** [comment] 2015-06-27 18:28
Thanks @jaykappa, these are looking really good. @lovegushwa and @cassiemc can you select two and give final feedback so Jay can finish these up?

**Comment by jaykappa** [comment] 2015-06-29 16:43
@cassiemc @lovegushwa here are the assets that need selections:

Mofo Email Callout/Facebook/Twitter (2 to be selected):
https://redpen.io/jmd1fe0a33abe69672

Teach.Org Banner (1 to be selected):
https://redpen.io/cj5346b0097f53c477

**Comment by cassiemc** [comment] 2015-06-29 21:37
@jaykappa – 

Mofo email callout – needs refinement on the spacing, hierarchy, text weight & color. @lovegushwa should inform you on the fira weight to use for the headline. Left some comments in the redpen, but generally prefer the bottom placement of elements (it's unlabeled but would've been D I guess?)

Teach.org banner – I prefer the patterned options. Would just fix the margins a big, and try one more with the plum shade instead of the brighter purple. #414468 Then we can choose between the blue and the plum.

**Comment by jaykappa** [comment] 2015-06-29 23:00
Thanks @cassiemc please see below for the **Teach.org banner** 

![2015-webmaker-teachorg-eng-v3](https://cloud.githubusercontent.com/assets/1036635/8420495/f10b543c-1e90-11e5-8b16-62ddf4f6473f.jpg)

Mofo email callout - I'll stay on standby. for details via @lovegushwa but will work with "D"

**Comment by cassiemc** [comment] 2015-06-30 16:27
I think A&B are working well, just not sure about the white text on yellow button. Will check out the UI toolkit for consistency. @lovegushwa can you please design R? these?

**Comment by jaykappa** [comment] 2015-07-01 01:23
Thanks @cassiemc when I took a peek at the UI the text was white, but it was Upper and lower case not all uppercase.

**Comment by jaykappa** [comment] 2015-07-01 01:26
Thanks for the poster file @lovegushwa the revised Mofo Email callout was applied accordingly plus with the revisions previously if ya can R? @cassiemc 

![2015-webmaker-mofo-eng-v3](https://cloud.githubusercontent.com/assets/1036635/8445671/5561e86e-1f6e-11e5-9a50-9dfa7d589f68.png)

Should note that with making margins the same for logo on top as on it's sides and enlarging the phone the logo doesn't seem to breathe as much, but if smaller and not perfect margins on top (option B) it feels stronger to me.

**Comment by lovegushwa** [comment] 2015-07-03 18:12
@cassiemc @jaykappa These are a hot mess but I was thinking about how to simplify the numbe of elements in the composition.  I experimented with braking the lockup and more aggressive phone cropping. (maybe mozilla webmaker should be bold and discover. create. share in book weight.) Anyhow maybe breaking away from the lockup will give us a bit more flexibility. Also we could look at an alternative to the button like this: Discover. Create. Share." ... "Download Mozilla Webmaker." I'm off today but will check in on Monday.

![screen shot 2015-07-03 at 10 54 35 am](https://cloud.githubusercontent.com/assets/12228435/8503336/9e0fd17e-2172-11e5-9a1e-57ce1fb53439.png)

**Comment by cassiemc** [comment] 2015-07-03 18:23
@lovegushwa I really like the tighter cropping of the phone! Maybe amend it to include the + button. I'm not a fan of breaking the lockup though. Here's a really quick example of the kind of hierarchy I am after with the headline + image + button (colors, pattern, exact sizes and margins to be tightened up accordingly) cc @jaykappa 
![email-banner](https://cloud.githubusercontent.com/assets/1186326/8503548/d9401436-218e-11e5-9291-a5efbba3b829.png)

**Comment by cassiemc** [comment] 2015-07-03 18:29
Re the teach.org banner, @jaykappa are you going to update it with a new screen? I'm happy with the general layout but I wonder if we can shorten the copy by a line. cc @KevZawacki

**Comment by jaykappa** [comment] 2015-07-03 19:12
@cassiemc here's the updated Teach.org with the new screen.

![2015-webmaker-teach-eng-v4](https://cloud.githubusercontent.com/assets/1036635/8503943/ec4660e2-2195-11e5-97b5-c4b43cfaa980.png)

**Comment by KevZawacki** [comment] 2015-07-06 13:48
@jaykappa @cassiemc 

If we're planning to shorten the copy to two lines:

"Webmaker lets you build and share original content
on your smartphone. Start creating in minutes."

**Comment by jaykappa** [comment] 2015-07-06 16:44
Just an update for the Mofo Callout if lockup can't be broken. @cassiemc @lovegushwa 

![webmaker-mofo_callout-eng-v7](https://cloud.githubusercontent.com/assets/1036635/8527810/bdd1d18a-23dc-11e5-9649-c5a642b90fef.png)

**Comment by lovegushwa** [comment] 2015-07-06 19:40
@jaykappa We need to move ahead with the lockup for now. You can get access to a PDF screens in every language in Webmaker Launch Assets > PROCESS > Webmaker-Screens.pdf

**Comment by cassiemc** [comment] 2015-07-06 19:44
I dig C & D, nice work @jaykappa! @lovegushwa will you review them for pixel perfection?

**Comment by jaykappa** [comment] 2015-07-06 19:51
Sounds good @lovegushwa and great to hear @cassiemc - I'll wait for any other tidbits of adjustments and we can move forward.

**Comment by lovegushwa** [comment] 2015-07-07 00:49
Awesome @jaykappa I think we should go ahead with D. Let's meet up tomorrow morning after or during stand up and sort through the details together.

**Comment by jaykappa** [comment] 2015-07-07 02:09
Amazing @lovegushwa ! I'm free all day tomorrow shoot me an email and I'll be ready to go through things.

**Comment by jaykappa** [comment] 2015-07-07 22:51
R? @cassiemc @lovegushwa Here is a red pen url to review the assets at this point: 
https://redpen.io/p/ch9b83172b72ab93bf

**Comment by cassiemc** [comment] 2015-07-08 14:27
@jaykappa Left a bunch of comments! Would be great to see an update today if possible.

**Comment by jaykappa** [comment] 2015-07-08 14:50
Thanks @cassiemc on it right now. All changes applied except for web banners, but that should be done soon and will be uploaded to Red Pen this afternoon.

**Comment by HPaulJohnson** [comment] 2015-07-09 22:36
Adding a new deliverable to create a Webmaker email template for BSD. Tracking in https://github.com/mozilla/webmaker-launch/issues/91

**Comment by lovegushwa** [comment] 2015-07-10 00:30
@jaykappa @cassiemc @HPaulJohnson 

A few ideas for the mix. I'm really most interested in resolving the horizontal banner. The vertical banners tend to work out because you can left alight elements. An issue with horizontal banners is shifting baselines when trying to align with the logo. Also we often end up with 3 competing visual elements. Using an icon based download button creates a varied mix of widths of elements. I think it's a bit more pleasing spatially.

![1](https://cloud.githubusercontent.com/assets/12228435/8609806/e98f9a1c-265e-11e5-9e6d-b04708262887.png)

![2](https://cloud.githubusercontent.com/assets/12228435/8609807/ee9f09a2-265e-11e5-9abe-267653317afa.png)

**Comment by cassiemc** [comment] 2015-07-10 16:18
I like the download button and am okay with the light purple text. I don't think it's really necessary but I defer! The download icon is cool and I like the varied widths of the columns... Would just even out the margins on the left and right side of the 'discover, create,share' block as it feels a little too far to the right imo.

**Comment by jaykappa** [comment] 2015-07-10 16:26
I'm happy with those alterations as well! greatness @lovegushwa
Here's the implementations of the previous comments prior to these on RedPen:

**Edit: Updated URL**
https://redpen.io/p/kd1c6243cb0d99e41c

**Comment by jaykappa** [comment] 2015-07-10 21:16
**Squares**
![2015-webmaker-webbanners-square-200x200](https://cloud.githubusercontent.com/assets/1036635/8629162/f27ee722-2726-11e5-9e63-7283e1958b5a.jpg)
![2015-webmaker-webbanners-square-250x250](https://cloud.githubusercontent.com/assets/1036635/8629163/f27fc3e0-2726-11e5-9d6b-7e014b499c90.jpg)

**Horizontals**
![2015-webmaker-webbanners-horz-728x90-v1](https://cloud.githubusercontent.com/assets/1036635/8629172/028da0a4-2727-11e5-96b1-cdb850c40d51.jpg)
![2015-webmaker-webbanners-horz-728x90-v2](https://cloud.githubusercontent.com/assets/1036635/8629170/0289c45c-2727-11e5-8b4f-ffe70faf77b9.jpg)
![2015-webmaker-webbanners-horz-728x90-v3](https://cloud.githubusercontent.com/assets/1036635/8629171/028d7912-2727-11e5-8114-a66e3c7125cb.jpg)
![2015-webmaker-webbanners-horz-728x90-v4](https://cloud.githubusercontent.com/assets/1036635/8629175/028eed06-2727-11e5-89d1-598a489912d9.jpg)
![2015-webmaker-webbanners-horz-728x90-v5](https://cloud.githubusercontent.com/assets/1036635/8629173/028dfe0a-2727-11e5-932b-db16ab0832d2.jpg)
![2015-webmaker-webbanners-horz-728x90-v6](https://cloud.githubusercontent.com/assets/1036635/8629174/028df5ea-2727-11e5-8cc8-1eacb45215bf.jpg)
![2015-webmaker-webbanners-horz-300x250](https://cloud.githubusercontent.com/assets/1036635/8629185/142ee034-2727-11e5-862d-ddbbf6f0a1e5.jpg)
![2015-webmaker-webbanners-horz-468x60](https://cloud.githubusercontent.com/assets/1036635/8629186/142fcd78-2727-11e5-9e1e-62bfbe309c87.jpg)

**Verticals**
![2015-webmaker-webbanners-vert-160x600](https://cloud.githubusercontent.com/assets/1036635/8629191/1fcea88e-2727-11e5-936d-9a4a3bc63235.jpg)
![2015-webmaker-webbanners-vert-300x600-v1](https://cloud.githubusercontent.com/assets/1036635/8629192/1fd12960-2727-11e5-934c-e0af2b15c0da.jpg)
![2015-webmaker-webbanners-vert-300x600-v2](https://cloud.githubusercontent.com/assets/1036635/8629193/1fd1c9f6-2727-11e5-934b-69ce28205e02.jpg)

The pixelation on the camera I can't fix because it's a Hue/Saturation aleration to the vector. If we revert/adjust the vector to match then that could help.

@cassiemc @lovegushwa @HPaulJohnson

**Comment by jaykappa** [comment] 2015-07-10 21:17
@edrushka @lovegushwa For localization I would need translations of the following please:

a) Download The App
b) Download (I technically have this, but just in case)
c) Webmaker lets you build and share original content on your smartphone. Start creating in minutes.
d) Learn More

**Comment by cassiemc** [comment] 2015-07-13 13:33
Thanks @jaykappa! @vazquez @lovegushwa Could you guys help with the pixelation in phone on the above images? That's the last bit of visual correction we need to finalize these.

Re. the translations we should really aim to do that Mon/Tues of this week since Friday is @jaykappa's last day on the project, and would be great to get translator's approval before then. cc @HPaulJohnson

**Comment by KevZawacki** [comment] 2015-07-13 18:28
Re: translations, I've dropped requests into https://github.com/mozilla/webmaker-launch/issues/79#issuecomment-121001321, https://github.com/mozilla/webmaker-launch/issues/80#issuecomment-121001121 and https://github.com/mozilla/webmaker-launch/issues/47#issuecomment-121000810. Will keep all in this ticketed posted.

**Comment by lovegushwa** [comment] 2015-07-13 19:32
@jaykappa are you using the current version of "Webmaker-Screens.pdf" in _PROCESS?
I fixed the issue with the button. Also you will find all the localized screens.

**Comment by jaykappa** [comment] 2015-07-13 19:59
@lovegushwa I was using the one that went up maybe 5-6 days ago, the white stroke on the blue button needed to be outlined to prevent the pixelation which is fine, but the camera is the new issue. When reduced it pixelated. I'll eye drop the PDF and apply the changes to the camera vector component I have. Hopefully that'll fix everything.

**Comment by lovegushwa** [comment] 2015-07-13 21:47
@jaykappa Let me know if you need me to build a different kind of file for you than a PDF.

**Comment by jaykappa** [comment] 2015-07-13 22:01
Thanks @lovegushwa I'll do what I can tonight, and will throw it to you for review. it won't be the best solution but it'll work for digital assets

**Comment by KevZawacki** [comment] 2015-07-14 13:20
@jaykappa @lovegushwa @edrushka 

We have translations for the four outstanding phrases:
https://github.com/mozilla/webmaker-launch/issues/79#issuecomment-121001321
https://github.com/mozilla/webmaker-launch/issues/80#issuecomment-121001121
https://github.com/mozilla/webmaker-launch/issues/47#issuecomment-121000810

**Comment by jaykappa** [comment] 2015-07-14 13:22
Thank you @KevZawacki the camera pixelation renderings will be up shortly so localization can happen today as well @cassiemc @lovegushwa @edrushka

**Comment by jaykappa** [comment] 2015-07-14 13:51
Here's the WebBanners with the pixelation fixed for R? @cassiemc @lovegushwa 

![2015-webmaker-webbanners-horz-300x250](https://cloud.githubusercontent.com/assets/1036635/8674739/c7d2e976-2a0d-11e5-9a22-4d617cfa8a0f.jpg)
![2015-webmaker-webbanners-horz-728x90-v2](https://cloud.githubusercontent.com/assets/1036635/8674744/cb67dfb0-2a0d-11e5-965d-9ca1a5869350.jpg)
![2015-webmaker-webbanners-horz-728x90-v4](https://cloud.githubusercontent.com/assets/1036635/8674749/ce20d9b4-2a0d-11e5-8205-fbae7f63726e.jpg)
![2015-webmaker-webbanners-vert-160x600](https://cloud.githubusercontent.com/assets/1036635/8674758/d1ce5852-2a0d-11e5-9df7-24bb2991f9bc.jpg)
![2015-webmaker-webbanners-vert-300x600-v1](https://cloud.githubusercontent.com/assets/1036635/8674762/d3dcd254-2a0d-11e5-974f-f00fba45fdd3.jpg)
![2015-webmaker-webbanners-vert-300x600-v2](https://cloud.githubusercontent.com/assets/1036635/8674765/d5c9f90c-2a0d-11e5-9555-d52eaca3638f.jpg)

**Comment by cassiemc** [comment] 2015-07-14 14:33
I still see pixelation around the UI buttons. @jaykappa can you email me a zip file so I can see if it is just a web compression thing?

**Comment by cassiemc** [comment] 2015-07-14 17:04
The images were still pixelated in the zip. The original pdf is not pixelated, so it's probably something to do with the way the image is being placed into the file. Hoping @jaykappa can share his source file here so I can check it out. We'll get to the bottom of this! ;)

**Comment by jaykappa** [comment] 2015-07-14 17:27
Here's the source file for download @cassiemc :

https://dl.dropboxusercontent.com/u/3603970/2015-Webmaker-WebBanners-Eng-V10.zip

**Comment by cassiemc** [comment] 2015-07-14 20:16
The problem is definitely in the .ai file prior to export, 2015-Webmaker-WebBanners-Eng-V10.ai. You can see it clearly in the Phone-5.ai file as well – a thin white outline around the button that seems extraneous and odd. However even when I remove that, it looks fine up close up but zoomed out (or exported) it looks pixelated again. 

I realize this is a hassle but can't seem to correct the problem in illustrator. So what I would do is export all the backgrounds without the phone from illustrator then re-position the phones by placing the original pdf (Webmaker-Screens.pdf under Webmaker Launch Assets/_PROCESS) as a smart object and rejigging the details (the shadow and status bar) as needed with masks, or however you prefer to do it. Hacky is fine as long as it exports nice and crisp.

I tested to see that this worked and set up a psd file so you can see what I mean. PSD here: https://www.dropbox.com/sh/iptlmmtihu3t463/AABr6zaeOyoG5JsrCMGqpe5Ca?dl=0
![re-positioned](https://cloud.githubusercontent.com/assets/1186326/8683832/0ec7af4e-2a43-11e5-8151-b214a71b5a3c.jpg)

Sounds doable @jaykappa? Wish there were a better way but shouldn't take too long once you get going.

**Comment by jaykappa** [comment] 2015-07-14 20:23
Was hoping this wasn't going to be the case @cassiemc but it makes sense as the method to proceed in to ensure the no-aliasing. I'll do as much as I can as quickly as I can and post back once complete.

**Comment by jaykappa** [comment] 2015-07-14 21:41
Here it is @cassiemc - I hope it's perfect (fingers crossed)!

![2015-webmaker-webbanners-horizontal-300x250](https://cloud.githubusercontent.com/assets/1036635/8685849/8cd9aade-2a4f-11e5-8a83-75aae0e337db.jpg)
![2015-webmaker-webbanners-square-200x200](https://cloud.githubusercontent.com/assets/1036635/8685847/8cd77b24-2a4f-11e5-9125-1b42b8112c9c.jpg)
![2015-webmaker-webbanners-square-250x250](https://cloud.githubusercontent.com/assets/1036635/8685850/8cda40de-2a4f-11e5-9c55-fa2d7d62d9d6.jpg)
![2015-webmaker-webbanners-vertical-160x600](https://cloud.githubusercontent.com/assets/1036635/8685851/8cda8292-2a4f-11e5-8684-9b410f60216d.jpg)
![2015-webmaker-webbanners-vertical-300x600](https://cloud.githubusercontent.com/assets/1036635/8685848/8cd93b8a-2a4f-11e5-8d6a-7ea38750bee6.jpg)

**Comment by cassiemc** [comment] 2015-07-14 21:58
Woohoo!! Looks great to me, @jaykappa! R+. @lovegushwa you want to take a look as well before we close out the web banners?

**Comment by lovegushwa** [comment] 2015-07-14 22:42
@cassiemc @jaykappa Yay looks great! Jay if it's not a hassle can you kern in the period after the r on discover a hair?

**Comment by jaykappa** [comment] 2015-07-14 23:28
@lovegushwa not a problem I'll make it happen.
@cassiemc are translations needed for web banners?

**Comment by cassiemc** [comment] 2015-07-15 00:28
Good question. I'd imagine so, @HPaulJohnson / @edrushka can you confirm? ^^

**Comment by HPaulJohnson** [comment] 2015-07-15 00:31
Would be nice to have them translated so that we can make them available to local partners for use on their sites.

**Comment by lovegushwa** [comment] 2015-07-15 18:24
@jaykappa please post localized banners (or a single banner that includes all language on these issues and ask for a review from the community member that posted the translation.) #80 #47 #79 
Be sure to cc @KevZawacki @secretrobotron and myself so we can chase down a review if necessary. 

I can help with the Bangladesh localization if needed, it takes a little Adobe wrangling. Just send me a link to your illustrator file.

**Comment by jaykappa** [comment] 2015-07-15 19:19
Thanks @lovegushwa - I for sure believe the copy and paste might be off for Bangla. The AI's are all on Drive I just finished uploading. I'll post the translations up on each issue page now.

**Comment by brianking** [comment] 2015-07-23 14:13
Lets happening in issue #80. Anything left to do here?

**Comment by MartinDesigner** [comment] 2015-08-15 16:38
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Closed as completed** 2015-08-21 19:33 UTC
Labels: Marketing material
